# FROM RMARKDOWN
language: r
sudo: false
cache:
  packages: yes
pandoc_version: 1.19.2.1

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0
  matrix:
    - PANDOC_VERSION=default
    - PANDOC_VERSION=latest PATH=$HOME/bin:$PATH

before_install:
  - mkdir -p $HOME/bin
  - cd $HOME/bin
  - curl -LO https://travis-bin.yihui.name/pandoc.tar.gz
  - tar zxf pandoc.tar.gz
  - rm pandoc.tar.gz
  - chmod +x pandoc*
  - tlmgr install units
